<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Day 3 Predict using Machine Learning</name>
   <tag></tag>
   <elementGuidId>9fc3c8bf-9dac-434e-970d-bc8ba47d121d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='titleEventDetail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#titleEventDetail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>c0781b10-10d3-4e86-8b89-231da3831fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>titleEventDetail</value>
      <webElementGuid>0ed2667d-fea7-47ce-bf9f-97d830deb9b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Day 3: Predict using Machine Learning</value>
      <webElementGuid>50346217-2f7c-4352-b0fd-7859290a5d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;titleEventDetail&quot;)</value>
      <webElementGuid>b3724b17-785c-4243-8f88-6f65fc68ba24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='titleEventDetail']</value>
      <webElementGuid>4827f0be-eb48-4309-9ec5-a2395f9f3e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eventDetailBlock']/h1</value>
      <webElementGuid>574efa66-4c55-473d-9222-0124b3702332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Day 3: Predict using Machine Learning'])[1]/following::h1[1]</value>
      <webElementGuid>c3bc9c54-5bff-41c7-91cc-92a7bc4ae5b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Events'])[1]/following::h1[1]</value>
      <webElementGuid>98168776-9cbc-482f-ae9a-99c0c79ae0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ziyad Syauqi Fawwazi'])[1]/preceding::h1[1]</value>
      <webElementGuid>2774d239-41af-4ea1-b101-c8ae70fb0eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Scientist Market Leader Company in Automotive Industry'])[1]/preceding::h1[1]</value>
      <webElementGuid>8c67f42d-076c-480b-89cf-d2dbe19a59b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>b7bfe55b-a61c-44d7-9d3d-545ec042dc2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'titleEventDetail' and (text() = 'Day 3: Predict using Machine Learning' or . = 'Day 3: Predict using Machine Learning')]</value>
      <webElementGuid>5701b268-1ac2-4f4b-833b-b1cd886e88e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
